apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi-container
        image: anirudhwb/cicd:latest
        ports:
        - containerPort: 5000