apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
spec:
  selector:
    app: weatherapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001    # Specify a static port for NodePort
  type: NodePort        # Change the service type to NodePort